modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="MIT"

[[mods]] #mandatory
modId="rubidium_dynamiclights" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Magnesium/Rubidium Dynamic Lights" #mandatory
logoFile="icon.png" #optional
credits="TeamDeusVult" #optional
authors="TexTrue,TexStudio-i18nProject" #optional
description='''
Adds Dynamic Lights to Magnesium/Rubidium.
'''

[[dependencies.rubidium_dynamiclights]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.rubidium_dynamiclights]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
