modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
issueTrackerURL="https://github.com/ForgeModi18n/MgRbDynamicLights-i18n/issues" #optional
license="MIT"

[[mods]] #mandatory
modId="rubidium_dynamiclights" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Rubidium Dynamic Lights" #mandatory
displayURL="https://github.com/ForgeModi18n/MgRbDynamicLights-i18n" #optional
logoFile="icon.png" #optional
credits="TeamDeusVult" #optional
authors="TexTrue,TexStudio-i18nProject" #optional
description='''
Adds Dynamic Lights to Rubidium.
'''

[[dependencies.rubidium_dynamiclights]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.rubidium_dynamiclights]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
