modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="MIT"

[[mods]] #mandatory
modId="dynamiclightsreforged" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Rubidium Dynamic Lights" #mandatory
logoFile="icon.png" #optional
credits="TeamDeusVult" #optional
authors="TexTrue,TexStudio-i18nProject" #optional
description='''
Adds Dynamic Lights to Rubidium.
'''

[[dependencies.dynamiclightsreforged]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.dynamiclightsreforged]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
